Make: Parallel backends CI

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -62,7 +62,7 @@ jobs:
       - name: Install dependencies
         run: |
           sudo apt update
-          sudo apt install -y cmake build-essential libjemalloc-dev libomp-dev gcc-12 g++-12
+          sudo apt install -y cmake build-essential gcc-12 g++-12
 
       - name: Build C/C++
         run: |
@@ -225,6 +225,125 @@ jobs:
       #   run: swift build -c release --static-swift-stdlib
       # - name: Test Swift
       #   run: swift test -c release --enable-test-discovery
+
+  test_ubuntu_gcc_cpus:
+    name: Ubuntu (GCC 12) StringZillas-CPUs
+    runs-on: ubuntu-22.04
+    env:
+      CC: gcc-12
+      CXX: g++-12
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+        # C/C++
+      - name: Install dependencies
+        run: |
+          sudo apt update
+          sudo apt install -y cmake build-essential gcc-12 g++-12
+
+      - name: Build C/C++
+        run: |
+          cmake -B build_artifacts \
+            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
+            -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
+            -DSTRINGZILLA_BUILD_BENCHMARK=1 \
+            -DSTRINGZILLA_BUILD_TEST=1
+
+          cmake --build build_artifacts --config RelWithDebInfo > build_artifacts/logs.txt 2>&1 || {
+            echo "Compilation failed. Here are the logs:"
+            cat build_artifacts/logs.txt
+            echo "The original compilation commands:"
+            cat build_artifacts/compile_commands.json
+            echo "CPU Features:"
+            lscpu
+            echo "GCC Version:"
+            gcc-12 --version
+            echo "G++ Version:"
+            g++-12 --version
+            exit 1
+          }
+      - name: Test C++
+        run: build_artifacts/stringzilla_test_cpp20
+
+        # Python StringZillas-CPUs
+      - name: Set up Python ${{ env.PYTHON_VERSION }}
+        uses: actions/setup-python@v5.2.0
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+      - name: Install uv
+        run: |
+          python -m pip install --upgrade pip
+          pip install uv
+      - name: Build Python StringZillas-CPUs
+        run: |
+          uv pip install pytest pytest-repeat numpy pyarrow
+          SZ_TARGET=stringzillas-cpus uv pip install -e . --force-reinstall --no-build-isolation
+      - name: Test Python StringZillas-CPUs
+        run: uv run --no-project python -m pytest scripts/test_stringzillas.py -s -x
+
+  test_ubuntu_clang_cpus:
+    name: Ubuntu (Clang 16) StringZillas-CPUs
+    runs-on: ubuntu-22.04
+    env:
+      CC: clang-16
+      CXX: clang++-16
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+        # C/C++
+      - name: Install dependencies
+        run: |
+          sudo apt update
+          sudo apt install -y cmake build-essential
+          wget https://apt.llvm.org/llvm.sh
+          chmod +x llvm.sh
+          sudo ./llvm.sh 16
+
+      - name: Build C/C++
+        run: |
+          cmake -B build_artifacts \
+            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
+            -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
+            -DSTRINGZILLA_BUILD_BENCHMARK=1 \
+            -DSTRINGZILLA_BUILD_TEST=1
+
+          cmake --build build_artifacts --config RelWithDebInfo > build_artifacts/logs.txt 2>&1 || {
+            echo "Compilation failed. Here are the logs:"
+            cat build_artifacts/logs.txt
+            echo "The original compilation commands:"
+            cat build_artifacts/compile_commands.json
+            echo "CPU Features:"
+            lscpu
+            echo "Clang Version:"
+            clang-16 --version
+            echo "Clang++ Version:"
+            clang++-16 --version
+            exit 1
+          }
+      - name: Test C++
+        run: build_artifacts/stringzilla_test_cpp20
+
+        # Python StringZillas-CPUs
+      - name: Set up Python ${{ env.PYTHON_VERSION }}
+        uses: actions/setup-python@v5.2.0
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+      - name: Install uv
+        run: |
+          python -m pip install --upgrade pip
+          pip install uv
+      - name: Build Python StringZillas-CPUs
+        run: |
+          uv pip install pytest pytest-repeat numpy pyarrow
+          SZ_TARGET=stringzillas-cpus uv pip install -e . --force-reinstall --no-build-isolation
+      - name: Test Python StringZillas-CPUs
+        run: uv run --no-project python -m pytest scripts/test_stringzillas.py -s -x
 
   # Temporary workaround to run Swift tests on Linux
   # Based on: https://github.com/swift-actions/setup-swift/issues/591#issuecomment-1685710678
@@ -474,6 +593,8 @@ jobs:
       [
         test_ubuntu_gcc,
         test_ubuntu_clang,
+        test_ubuntu_gcc_cpus,
+        test_ubuntu_clang_cpus,
         test_macos,
         test_windows,
         test_alpine,
