Make: Add CUDA to GitHub CI

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -112,7 +112,7 @@ jobs:
 
         # Python
       - name: Set up Python ${{ env.PYTHON_VERSION }}
-        uses: actions/setup-python@v5.2.0
+        uses: actions/setup-python@v5.6.0
         with:
           python-version: ${{ env.PYTHON_VERSION }}
       - name: Build Python
@@ -197,7 +197,7 @@ jobs:
 
         # Python
       - name: Set up Python ${{ env.PYTHON_VERSION }}
-        uses: actions/setup-python@v5.2.0
+        uses: actions/setup-python@v5.6.0
         with:
           python-version: ${{ env.PYTHON_VERSION }}
       - name: Build Python
@@ -270,20 +270,80 @@ jobs:
 
         # Python StringZillas-CPUs
       - name: Set up Python ${{ env.PYTHON_VERSION }}
-        uses: actions/setup-python@v5.2.0
+        uses: actions/setup-python@v5.6.0
         with:
           python-version: ${{ env.PYTHON_VERSION }}
-      - name: Install uv
-        run: |
-          python -m pip install --upgrade pip
-          pip install uv
       - name: Build Python StringZillas-CPUs
         run: |
           pip install pytest pytest-repeat numpy pyarrow wheel
           SZ_TARGET=stringzilla pip install -e . --force-reinstall --no-build-isolation
           SZ_TARGET=stringzillas-cpus pip install -e . --force-reinstall --no-build-isolation
       - name: Test Python StringZillas-CPUs
-        run: uv run --no-project python -m pytest scripts/test_stringzillas.py -s -x
+        run: python -m pytest scripts/test_stringzillas.py -s -x
+
+  test_ubuntu_cuda:
+    name: Ubuntu (StringZillas-CUDA)
+    runs-on: ubuntu-22.04
+    env:
+      CC: gcc-12
+      CXX: g++-12
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+        # Install CUDA Toolkit
+      - name: Install CUDA Toolkit
+        uses: Jimver/cuda-toolkit@v0.2.26
+        with:
+          cuda: "12.9.1"
+          method: "network"
+
+        # C/C++
+      - name: Install dependencies
+        run: |
+          sudo apt update
+          sudo apt install -y cmake build-essential gcc-12 g++-12
+
+      - name: Build C/C++ with CUDA
+        run: |
+          cmake -B build_artifacts \
+            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
+            -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
+            -DSTRINGZILLA_BUILD_BENCHMARK=1 \
+            -DSTRINGZILLA_BUILD_TEST=1
+
+          cmake --build build_artifacts --config RelWithDebInfo > build_artifacts/logs.txt 2>&1 || {
+            echo "Compilation failed. Here are the logs:"
+            cat build_artifacts/logs.txt
+            echo "The original compilation commands:"
+            cat build_artifacts/compile_commands.json
+            echo "CPU Features:"
+            lscpu
+            echo "CUDA Version:"
+            nvcc --version
+            echo "GCC Version:"
+            gcc-12 --version
+            echo "G++ Version:"
+            g++-12 --version
+            exit 1
+          }
+      - name: Test C++
+        run: build_artifacts/stringzilla_test_cpp20
+
+        # Python StringZillas-CUDA
+      - name: Set up Python ${{ env.PYTHON_VERSION }}
+        uses: actions/setup-python@v5.6.0
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+      - name: Build Python StringZillas-CUDA
+        run: |
+          pip install pytest pytest-repeat numpy pyarrow wheel
+          SZ_TARGET=stringzilla pip install -e . --force-reinstall --no-build-isolation
+          SZ_TARGET=stringzillas-cuda pip install -e . --force-reinstall --no-build-isolation
+      - name: Test Python StringZillas-CUDA
+        run: python -m pytest scripts/test_stringzillas.py -s -x
 
   # Temporary workaround to run Swift tests on Linux
   # Based on: https://github.com/swift-actions/setup-swift/issues/591#issuecomment-1685710678
@@ -393,7 +453,7 @@ jobs:
 
         # Python
       - name: Set up Python ${{ env.PYTHON_VERSION }}
-        uses: actions/setup-python@v5.2.0
+        uses: actions/setup-python@v5.6.0
         with:
           python-version: ${{ env.PYTHON_VERSION }}
       - name: Build Python
@@ -467,7 +527,7 @@ jobs:
 
         # Python
       - name: Set up Python ${{ env.PYTHON_VERSION }}
-        uses: actions/setup-python@v5.2.0
+        uses: actions/setup-python@v5.6.0
         with:
           python-version: ${{ env.PYTHON_VERSION }}
       - name: Build Python
@@ -529,15 +589,7 @@ jobs:
   build_wheels:
     name: Build Python ${{ matrix.python-version }} for ${{ matrix.os }}
     runs-on: ${{ matrix.os }}
-    needs:
-      [
-        test_ubuntu_gcc,
-        test_ubuntu_clang,
-        test_ubuntu_cpus,
-        test_macos,
-        test_windows,
-        test_alpine,
-      ]
+    needs: [test_ubuntu_gcc, test_ubuntu_clang, test_macos, test_windows]
     strategy:
       matrix:
         os: [ubuntu-24.04, macos-13, windows-2022]
@@ -547,7 +599,7 @@ jobs:
         with:
           submodules: recursive
       - name: Set up Python
-        uses: actions/setup-python@v5.2.0
+        uses: actions/setup-python@v5.6.0
         with:
           python-version: 3.x
 
